// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a line in the loot filter block.
 * The `name` field is the line name; `params` holds all following parameters.
 */
export type BlockItem = { name: string; params: Array<string> };
