// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockItem } from "./BlockItem";
import type { BlockName } from "./BlockName";

/**
 * Represents a parsed Block which holds a block name and its parsed block items.
 */
export type Block = {
  order: number;
  name: BlockName;
  items: { [key in string]?: Array<BlockItem> };
};
